# Generated by Django 6.0 on 2026-02-03 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AddField(
            model_name='plant',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Detailed care instructions including soil, fertilizer, pruning, etc.'),
        ),
        migrations.AddField(
            model_name='plant',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner Friendly'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Care difficulty level for growers', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, help_text="Plant family classification (e.g., 'Solanaceae')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_rate',
            field=models.CharField(blank=True, help_text="Growth rate (e.g., 'Fast', 'Moderate', 'Slow')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image of the plant', null=True, upload_to='plants/images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False, help_text='Whether the plant produces edible parts'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_medicinal',
            field=models.BooleanField(default=False, help_text='Whether the plant has medicinal properties'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_toxic',
            field=models.BooleanField(default=False, help_text='Whether the plant is toxic to humans or pets'),
        ),
        migrations.AddField(
            model_name='plant',
            name='mature_height',
            field=models.CharField(blank=True, help_text="Expected height at maturity (e.g., '1-2 meters')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='max_temperature',
            field=models.IntegerField(blank=True, help_text='Maximum temperature tolerance in Celsius', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_temperature',
            field=models.IntegerField(blank=True, help_text='Minimum temperature tolerance in Celsius', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_requirement',
            field=models.CharField(choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (4-6 hours)'), ('partial_shade', 'Partial Shade (2-4 hours)'), ('full_shade', 'Full Shade (< 2 hours)')], default='partial_sun', help_text='Amount of sunlight needed for optimal growth', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the plant record was last updated'),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_2_days', 'Every 2-3 Days'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often the plant needs watering under normal conditions', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the plant record was created'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the plant, its characteristics, and uses'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small icon for UI display', null=True, upload_to='plants/icons/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text="Common name of the plant (e.g., 'Tomato', 'Rose')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, help_text="Scientific/botanical name (e.g., 'Solanum lycopersicum')", max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['name'], name='plants_plan_name_abe05c_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['scientific_name'], name='plants_plan_scienti_00c7ff_idx'),
        ),
    ]
