# Generated by Django 6.0 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_options_plant_care_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text="Common name of the plant (e.g., 'Tomato', 'Rose')", max_length=100),
        ),
    ]
