# Generated by Django 6.0 on 2026-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='is_edible',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='is_medicinal',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='is_toxic',
        ),
        migrations.AddField(
            model_name='plant',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy')], default='healthy', help_text='Current health status of the plant', max_length=20),
        ),
    ]
