# Generated by Django 6.0 on 2026-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_plant_is_edible_remove_plant_is_medicinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('non_leaf', 'Non leaf image'), ('out_of_scope', 'Out of scope')], default='healthy', help_text='Current health status of the plant', max_length=20),
        ),
    ]
