# Generated by Django 6.0 on 2026-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sunlight_requirement',
            field=models.CharField(choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (4-6 hours)'), ('partial_shade', 'Partial Shade (2-4 hours)'), ('full_shade', 'Full Shade (< 2 hours)'), ('not_needed', 'Not Needed'), ('not_available', 'Not Available / Not in Database')], default='partial_sun', help_text='Amount of sunlight needed for optimal growth', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_2_days', 'Every 2-3 Days'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('not_needed', 'Not Needed'), ('not_available', 'Not Available / Not in Database')], default='weekly', help_text='How often the plant needs watering under normal conditions', max_length=20),
        ),
    ]
