# Generated by Django 6.0 on 2026-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_sunlight_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_non_plant',
            field=models.BooleanField(default=False, help_text='True if the image was identified as a non-plant object'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_out_of_scope',
            field=models.BooleanField(default=False, help_text='True if the plant exists but is not in our primary detection dataset'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('non_plant', 'Non-Plant Image'), ('out_of_scope', 'Outside Scope')], default='healthy', help_text='Current health status of the plant', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight_requirement',
            field=models.CharField(choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (4-6 hours)'), ('partial_shade', 'Partial Shade (2-4 hours)'), ('full_shade', 'Full Shade (< 2 hours)'), ('not_needed', 'Not Needed'), ('not_available', 'Not Available / Not in Database'), ('outside_scope', 'Outside Scope'), ('non_plant', 'Non-Plant Image')], default='partial_sun', help_text='Amount of sunlight needed for optimal growth', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_2_days', 'Every 2-3 Days'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('not_needed', 'Not Needed'), ('not_available', 'Not Available / Not in Database'), ('outside_scope', 'Outside Scope'), ('non_plant', 'Non-Plant Image')], default='weekly', help_text='How often the plant needs watering under normal conditions', max_length=20),
        ),
    ]
