# Generated by Django 6.0 on 2026-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coupon_category_icon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diseaseproductmapping',
            name='disease_name_ne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions_ne',
            field=models.TextField(blank=True, null=True),
        ),
    ]
