# Generated by Django 5.2.7 on 2026-02-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the disease', max_length=150)),
                ('symptoms', models.TextField(help_text='Detailed symptoms of the disease')),
                ('cause', models.TextField(blank=True, help_text='What causes this disease?')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='plants.plant')),
            ],
            options={
                'ordering': ['plant', 'name'],
                'unique_together': {('plant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=20)),
                ('title', models.CharField(help_text='Short title of the treatment', max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='diseases.disease')),
            ],
            options={
                'ordering': ['disease', 'type'],
            },
        ),
    ]
