# Generated by Django 6.0 on 2026-02-03 15:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
        ('plants', '0002_alter_plant_options_plant_care_instructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name'], 'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['disease', 'treatment_type', 'name'], 'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='type',
        ),
        migrations.AddField(
            model_name='disease',
            name='affected_plants',
            field=models.ManyToManyField(help_text='Plant species that can be affected by this disease', related_name='diseases', to='plants.plant'),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.TextField(blank=True, help_text='What causes this disease (e.g., fungal spores, bacteria, environmental conditions)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(choices=[('fungal', 'Fungal Disease'), ('bacterial', 'Bacterial Disease'), ('viral', 'Viral Disease'), ('pest', 'Pest Infestation'), ('nutritional', 'Nutritional Deficiency'), ('environmental', 'Environmental Stress')], default='fungal', help_text='Category of the disease', max_length=20),
        ),
        migrations.AddField(
            model_name='disease',
            name='favorable_conditions',
            field=models.TextField(blank=True, help_text="Environmental conditions that favor disease development (e.g., 'High humidity, warm temperatures')"),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_contagious',
            field=models.BooleanField(default=True, help_text='Whether the disease can spread to other plants'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_measures',
            field=models.TextField(blank=True, help_text='Steps to prevent this disease from occurring'),
        ),
        migrations.AddField(
            model_name='disease',
            name='scientific_name',
            field=models.CharField(blank=True, help_text="Scientific name of the pathogen (e.g., 'Phytophthora infestans')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(choices=[('mild', 'Mild - Minor damage, easy to treat'), ('moderate', 'Moderate - Noticeable damage, requires attention'), ('severe', 'Severe - Significant damage, urgent treatment needed'), ('critical', 'Critical - Life-threatening to plant')], default='moderate', help_text='How severe this disease typically is', max_length=20),
        ),
        migrations.AddField(
            model_name='disease',
            name='spread_rate',
            field=models.CharField(blank=True, help_text="How quickly the disease spreads (e.g., 'Fast', 'Moderate', 'Slow')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the disease record was last updated'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='application_frequency',
            field=models.CharField(blank=True, help_text="How often to apply the treatment (e.g., 'Every 7 days for 3 weeks')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='cost_estimate',
            field=models.CharField(blank=True, help_text="Approximate cost range (e.g., 'Low', 'Medium', 'High' or '$10-$20')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 3, 15, 12, 46, 734293, tzinfo=datetime.timezone.utc), help_text='Timestamp when the treatment was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='dosage_instructions',
            field=models.TextField(blank=True, help_text='Specific dosage and dilution instructions if applicable'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='effectiveness_rate',
            field=models.IntegerField(blank=True, help_text='Estimated effectiveness percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='treatment',
            name='expected_duration',
            field=models.CharField(blank=True, help_text="Expected time to see results (e.g., '1-2 weeks')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_preventive',
            field=models.BooleanField(default=False, help_text='Whether this treatment can be used preventively'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default=datetime.datetime(2026, 2, 3, 15, 13, 12, 841179, tzinfo=datetime.timezone.utc), help_text='Name of the treatment method', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='precautions',
            field=models.TextField(blank=True, help_text="Safety precautions and warnings (e.g., 'Wear gloves', 'Keep away from pets')"),
        ),
        migrations.AddField(
            model_name='treatment',
            name='products_needed',
            field=models.TextField(blank=True, help_text="List of products, tools, or materials needed (e.g., 'Neem oil, spray bottle, protective gloves')"),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('organic', 'Organic/Natural'), ('chemical', 'Chemical/Synthetic'), ('biological', 'Biological Control'), ('cultural', 'Cultural Practice'), ('mechanical', 'Mechanical/Physical')], default='organic', help_text='Category of treatment approach', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the treatment was last updated'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the disease record was created'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the disease and its impact'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, help_text='Image showing disease symptoms', null=True, upload_to='diseases/images/'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text="Common name of the disease (e.g., 'Tomato Late Blight')", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(help_text='Detailed description of visible symptoms (e.g., leaf spots, wilting, discoloration)'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(help_text='Overview of the treatment method and how it works'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(help_text='The disease this treatment addresses', on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='diseases.disease'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='instructions',
            field=models.TextField(help_text='Detailed step-by-step instructions for applying the treatment'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='diseases_di_name_f1e1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['disease_type'], name='diseases_di_disease_caf0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['severity_level'], name='diseases_di_severit_fafc41_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['disease', 'treatment_type'], name='diseases_tr_disease_c54098_idx'),
        ),
        migrations.RemoveField(
            model_name='disease',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='plant',
        ),
    ]
