# Generated by Django 6.0 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_options_alter_treatment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text="Common name of the disease (e.g., 'Tomato Late Blight')", max_length=150),
        ),
    ]
