# Generated by Django 6.0 on 2026-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_disease_name'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Products from the store that are recommended for this treatment', related_name='treatments', to='ecommerce.product'),
        ),
    ]
