# Generated by Django 6.0 on 2026-04-06 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content (kg/ha)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content (kg/ha)')),
                ('potassium', models.FloatField(help_text='Potassium content (kg/ha)')),
                ('ph_level', models.FloatField(help_text='Soil pH (0-14)')),
                ('moisture', models.FloatField(help_text='Moisture percentage (0-100)')),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], default='loamy', max_length=20)),
                ('health_score', models.IntegerField(default=0, help_text='Computed 0-100 score')),
                ('deficiencies', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('suggested_products', models.JSONField(default=list, help_text='Product IDs from ecommerce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soil Analysis',
                'verbose_name_plural': 'Soil Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
