# Generated by Django 6.0 on 2026-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilanalysis',
            name='organic_matter',
            field=models.FloatField(blank=True, help_text='Organic matter percentage (0-15%)', null=True),
        ),
    ]
